### ISSUE TITLE
FF Nightly has an improvement which should be incorporated into the spec

### ISSUE THREAD

**Issue by erights** [domenic/window-proxy-spec#4]
FF Nightly deviates from this spec in a way I like. The spec should be updated to conform to this behavior:

> Object.getOwnPropertyDescriptor(window, 'NaN')
Object { value: NaN, writable: false, enumerable: false, configurable: false }

> Object.getOwnPropertyDescriptor(window, 'Infinity')
Object { value: Infinity, writable: false, enumerable: false, configurable: false }

> Object.getOwnPropertyDescriptor(window, 'undefined')
Object { value: undefined, writable: false, enumerable: false, configurable: false }

The issue is that these three properties specifically necessarily exist in exactly the same way on all Window objects, and therefore will always appear the same way on all WindowProxy objects. Thus, for these, no invariant is violated by claiming they are non-configurable. They cannot be affected by navigating the frame.

**Comment by domenic** [comment]
Pull requests welcome :).

@bzbarsky, was this intentional? It's hard to imagine there's actual code in Firefox that checks if the property is one of those three...

**Comment by bzbarsky** [comment]
Firefox doesn't really implement this spec yet.  In particular, it will happily report properties as non-configurable, not just in those three cases.

The general Firefox status for this stuff is as follows:

1. Firefox nightlies have https://bugzilla.mozilla.org/show_bug.cgi?id=1107443 fixed, so explicitly trying to define a non-configurable property will throw.  This is only enabled in nightly and aurora (developer edition) for now.
2. https://bugzilla.mozilla.org/show_bug.cgi?id=1178638 tracks enabling this for all channels.
3. Once that's done, https://bugzilla.mozilla.org/show_bug.cgi?id=1178639 tracks reporting properties as always configurable.

That said, we probably _could_ special-case these three particular property names without any problems arising, if that's desired.

**Comment by erights** [comment]
I don't feel strongly that we should special case it. There is of course *much* to be said for *not* adding special cases. However, if FF does not already implement this special case, how is it that I'm seeing the behavior I quoted at the top of this issue?

**Comment by bzbarsky** [comment]
@erights Which behavior is confusing you, exactly?  Right now Firefox will allow you to define non-configurable properties on a Window and if you do so, will claim they are non-configurable when you call `getOwnPropertyDescriptor`.  Is that all you're seeing?

**Comment by erights** [comment]
On FF Nightly, when I ask

    > Object.getOwnPropertyDescriptor(window, 'NaN')

I get the response

    Object { value: NaN, writable: false, enumerable: false, configurable: false }

In other words, the *WindowProxy* claims that this property is non-configurable. I don't understand how I would see this if the implementation has no special case.

**Comment by bzbarsky** [comment]
Special case for what, exactly?  The property is actually non-configurable on the `Window` object; the `WindowProxy` just reports that truthfully (until I fix <https://bugzilla.mozilla.org/show_bug.cgi?id=1178639>).

Here's a similar example that doesn't involve NaN:

    var nonSpecialCasedName = 5;
    alert(JSON.stringify(Object.getOwnPropertyDescriptor(window, 'nonSpecialCasedName')))

Just make sure to run that in an actual web page, not in the console, because `var` in the console is a bit weird.

**Comment by erights** [comment]
> just reports that truthfully (until I fix https://bugzilla.mozilla.org/show_bug.cgi?id=1178639).

That was indeed the source of my confusion, thanks. Seeing the new defineProperty behavior I had assumed that FF nightly was also already implementing the getOwnProperty behavior.

With that clarified, I withdraw the request for a special case. I'd rather have things be simpler -- the way this draft spec currently reads. I'm closing this bug.
