### ISSUE TITLE
How does [[DefineOwnProperty]] implementation not cause top-level var declarations to throw?

### ISSUE THREAD

**Issue by michaelficarra** [domenic/window-proxy-spec#5]
0. `GlobalDeclarationInstantiation` calls `CreateGlobalVarBinding` for each top-level var, with the `D` parameter set to `false`.
0. `CreateGlobalVarBinding` calls `CreateMutableBinding` with the `D` parameter set to `false`.
0. `CreateMutableBinding` calls `DefinePropertyOrThrow` with a property descriptor that has a `[[Configurable]]` value of `false`.
0. `DefinePropertyOrThrow` calls `[[DefineOwnProperty]]` with that same descriptor.
0. `[[DefineOwnProperty]]`, as defined here, throws a **TypeError**.

**Comment by domenic** [comment]
Hmm, this spec has moved, I should tombstone it. Please see the updated version at https://html.spec.whatwg.org/#the-windowproxy-exotic-object which incorporates some changes. @annevk has taken over this issue.
